variableGroups:
  - title: PRODX Pilot OCI
    variables:
      - compartment_ocid
      - vcn_ocid
      - ssh_public_key
      - region
      - public_subnet_cidr
      - instance_name
      - ocpus
      - memory_in_gbs
